# Generated by Django 4.2.2 on 2023-07-02 07:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog_app', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='likeblog',
            unique_together={('blog', 'created_by')},
        ),
    ]
